# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
require: 
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/channels/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation 

# RSpec configuration
RSpec/ExampleLength:
  Max: 10 # Adjust the maximum example length as per your project's guidelines
  CountKeywords: false # Set to true to count 'it' and 'specify' as part of the length